user_token: OTY3NmVjYWYtZTJhNC00NzNhLTgwM2YtZGY3OTBkYTM3YWFhXzgxMzQ=

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: localhost
  port: 5432
  user: kts_user
  password: kts_pass
  database: kts
bot:
  token: vk1.a.tV4G1GPuH8mX2exvXMX-KfJSkPBpsdeSk5TOCWYNTyRU0XZ1sadJcgXeK3hVBNttjIuYhu2p3tekeucFirFn-X7cCtgYOBNbrjg_Rxq7ZiO_8NdweocKjdm7nqza05Bto23a8t3cqy8NnpZTPO4MvJnVO9rIGoaxfi5EOsgH4KjSIhBj4BgqHNPRqFwWxhpBYszdvfy72rk25OvlqSAvhQ
  group_id: 229818931


