"""changed adminmodel

Revision ID: b0b0e06e2dc4
Revises: db715c6b27f0
Create Date: 2025-03-28 23:23:27.280241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b0e06e2dc4'
down_revision: Union[str, None] = 'db715c6b27f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('admins', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('admins', 'password')
    # ### end Alembic commands ###
