"""updated cascade delete

Revision ID: d0065adfdabc
Revises: b0b0e06e2dc4
Create Date: 2025-03-29 14:49:09.688736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0065adfdabc'
down_revision: Union[str, None] = 'b0b0e06e2dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_question_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('questions_theme_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'themes', ['theme_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_theme_id_fkey', 'questions', 'themes', ['theme_id'], ['id'])
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_question_id_fkey', 'answers', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
